travis:
  secure:
    BINSTAR_TOKEN: jhqFZX1ysuTjC2o76BEjufpKkF28rHut7rX2dH8+Yina0bOcRaRUpXAyDte9m+/CJlBo33OsNSonK/xtp+gPhSCCgLYMHTNze78OfUFPa3rgU6I79120DCmmjM/q2y/PSQvYepSBFixdTgWP3l1vGj0KS6YQQo6L+xlsqDKVFxmvLrDYQUEvhNqogz7QBsbYVrrxBWOjiDlZTeMG1vhDL5ayvC4vhR9YFsqnmMd6e4UYQbEyw/FynG4nEWj29R0d/TPsE6xDzFwmxfhbwf8ax/gDy7pKn8uJKQpnR7CLumNEGYUFLtkXrjdoPOy+FPXblK77XHlmf+mds4Gxm04Q321g5nq7RMsZYZy0rNaDVyinINCytn2g/KJViIYxa9NUBB/oWlu+za93TOx5a9Pv6rpGY7ejsSj0ZgNPcaejYUckaEjaPmPIUkkHIed8xKLCJ3EpRNSBkRSYgxxSquGwMCTqPW4AqELqJcTY99T+iwiNORSOqqu1g4TkLJGlV4TB7DuAtQh4Ne4o78VBkWjhTXXd2Quf3rQyAc7uvaAUSYBxFPSndHgInUhZh4ZDa4V+wws/bUgGHfmAzDJqRSrHSjIkeJryhzfjzBp2xswRGtU0XFAjsPOThAOwCgKjbSb6j5pjFrDA6+aRmnw63W5/gvUBUj8CRaq1j8noINuXlvo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
